from typing import Protocol, Sequence

from atlas_ultimate_crm.domain.entities.contact import ContactEntity
from atlas_ultimate_crm.domain.entities.workspace import WorkspaceEntity


class ContactRepository(Protocol):
    def get_by_id(self, contact_id: str) -> ContactEntity | None: ...
    def get_by_phone(self, workspace_id: str, phone: str) -> ContactEntity | None: ...
    def list_by_workspace(self, workspace_id: str, search: str = "", limit: int = 100, offset: int = 0) -> Sequence[ContactEntity]: ...
    def count_by_workspace(self, workspace_id: str) -> int: ...
    def save(self, contact: ContactEntity) -> ContactEntity: ...
    def delete(self, contact_id: str) -> None: ...


class WorkspaceRepository(Protocol):
    def get_default(self) -> WorkspaceEntity | None: ...
    def save(self, workspace: WorkspaceEntity) -> WorkspaceEntity: ...
