from typing import Protocol, Callable, Any


class TaskQueue(Protocol):
    def enqueue(self, func: Callable, *args: Any, **kwargs: Any) -> str: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
